name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish .NET Core application
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish

      - name: Create deployment package
        run: zip -r deployment-package.zip ./publish/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Upload deployment package to S3
        run: |
          aws s3 cp deployment-package.zip s3://albapro/

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name testcicd ---code ImageUri=project-management:latest --runtime dotnet6 --role arn:aws:iam::767397959578:role/aws-service-role/sso.amazonaws.com/AWSServiceRoleForSSO --s3-bucket albapro --s3-key deployment-package.zip --region ap-southeast-1
